pipeline {
    agent {
        label 'slave'
    }
    tools {
        maven '3.8.4'
        jdk 'jdk8'
    }
    stages {
        stage('checkout') {
            steps {
                checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/kaviyakulothungan10/simple-java-maven-app.git']]]   
            }
        }
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
                bat 'echo helloworld'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
